### ISSUE TITLE
Allow linking to `object` in scaladsl and `class` in javadsl

### ISSUE THREAD

**Issue by raboof** [lightbend/sbt-paradox-apidoc#100]
JavaFlowSupport is an object without corresponding class in the scaladsl, and a ~inner~ regular class in javadsl. this is currently not supported, as we filter out all case objects that do not have a corresponding regular class.

**Comment by ennru** [comment]
This should now work by using the regular `@scaladsl` directive as it now understands inner classes. https://github.com/lightbend/paradox/pull/397

**Comment by raboof** [comment]
It works for `@scaladsl` but not for `@apidoc`, so we don't have a convenient way to link to scaladoc for scala users and javadoc for java users yet.

**Comment by ennru** [comment]
Isn't that the same problem as you discussed in https://github.com/lightbend/sbt-paradox-apidoc/issues/48#issuecomment-561658997 ?

**Comment by raboof** [comment]
No, I'd want it to link to `akka.stream.javadsl.JavaFlowSupport` for Java and to `akka.stream.scaladsl.JavaFlowSupport$` for Scala.
