### ISSUE TITLE
Apidoc creates a broken link if only object exists, but $ is missing

### ISSUE THREAD

**Issue by ennru** [lightbend/sbt-paradox-apidoc#154]
For objects without a "companion class" apidoc does not fail if the ending `$` is missing and creates a link to the non-existent regular class API docs page.

The problem is that the class exists in byte code and can't be easily distinguished from cases where both class and object exist in source code.

**Comment by raboof** [comment]
This would be great to fix, but seems like it would require having access to more than just the classpath. Alternatively, we could lobby for the scaladoc tool to generate a redirect for these classes.
