### ISSUE TITLE
Tests fail on jdk11

### ISSUE THREAD

**Issue by raboof** [lightbend/sbt-paradox-apidoc#62]
Since apparently jdk11 formats javadoc URL's differently (without the frames?)

**Comment by ennru** [comment]
That should be solvable with https://github.com/lightbend/paradox/pull/355 as this plugin's directive renders into paradox' `@javadoc` directive.

https://github.com/lightbend/sbt-paradox-apidoc/blob/51b3aa25ee7403464f88b20c660a791bf37aa87d/src/main/scala/com/lightbend/paradox/apidoc/ApidocDirective.scala#L83

**Comment by ennru** [comment]
Paradox itself creates different Javadoc links depending on the JDK version. So we might want to update the expected files to use the JDK 11 syntax. (But than they'll fail on JDK 8.)

**Comment by raboof** [comment]
sounds good to just pick one.

perhaps log an error when running on the 'unexpected' jdk version?

**Comment by ennru** [comment]
I've set the `javadoc.link_style` attribute so this should not be a problem anymore.
